encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
      path( ""                     , views.index,          name="index"        )
    , path( "addTitle/"            , views.addTitle,       name="addTitle"     )
    , path( "search/"              , views.search_title,   name='search'       ) 
    , path( "<str:TITLE>/edit"     , views.edit_title,     name="edit_title"   )
    , path( "<str:TITLE>"          , views.get_title,      name="get_title"    )   
    , path( "random_title/"        , views.random_title,   name="random_title" )
]

wiki/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( '', include( "encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.http.response import HttpResponseRedirect
from django.core.files.storage import default_storage
from django.template.loader import render_to_string
from django.shortcuts import render
from django.urls import reverse
import random

from . import util


class NewArticleForm( forms.Form ):
    Title = forms.CharField(label='Title ', required="true")
    description = forms.CharField( label='Description ', required="true", widget=forms.Textarea( attrs= { 'rows': 5, 'cols': 20 } ) )



def addTitle( request, Title = None ):
    ''' addTitle view '''
    context = {
        "NewArticle": NewArticleForm(),
        "Message": None
    }

    if request.method == "POST":
        form = NewArticleForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["Title"]
            description = form.cleaned_data['description']
            util.save_entry( title, description )
            return HttpResponseRedirect( reverse( "wiki:get_title", kwargs={'TITLE': title} ) )



    return render( request, "encyclopedia/addTitle.html", context ) 
    #return HttpResponseRedirect( reverse( "encyclopedia:addTitle", args=context))

def edit_title(request, TITLE ):
    form = NewArticleForm(request.POST or None)
    if TITLE != None and request.method == "GET":
        article = util.get_entry( TITLE )
        initial_data = {
            'Title': TITLE,
            'description': article
        }
        form.initial=initial_data

    if TITLE != None and request.method == 'POST':
        if form.is_valid():
            article = form.cleaned_data["description"]
            TITLE = form.cleaned_data['Title']
            util.save_entry( title=TITLE, content=article)
            return HttpResponseRedirect( reverse( "wiki:get_title", kwargs={'TITLE': TITLE} ) )

    return render( request, "encyclopedia/editTitle.html", 
                    {
                        "NewArticle": form,
                        "Message": "hhwhwhwhwhwhw"
                    }  
                 )


def index(request):
    ''' Home view '''
    return render(request, "encyclopedia/index.html", {
                    "entries": util.list_entries()
    })

def get_title(request, TITLE):
    ''' Retrieves a requested title '''
    result = message = None
    result = util.get_entry( TITLE )
    if result == None:
        message = f"Article not found for {TITLE}"
    else:
        result = util.print_markdown( result )
    return render( request, "encyclopedia/title.html", 
                    {
                        "article": result, 
                        "title": TITLE,
                        "message": message
                    } 
                  )


def search_title( request ):
    ''' Search solution entry point '''
    msg = None
    query = request.POST.get("q")
    articles = util.search_in_titles( query )
    qtty = len( articles )
    if( len(articles) == 0 ):
        msg = f'Search for "{query.upper()}" found no results'

    if( len( articles ) == 1):
        return HttpResponseRedirect( reverse( "wiki:get_title", args=articles))
    else:
        msg = f'Search for "{query.upper()}" found {qtty} results'
        return render( request, "encyclopedia/index.html",
                            {
                                "entries": articles,
                                "message": msg
                            }
                )

def random_title (request):
    ''' Random article entry point '''
    article = message = None
    selected_title = random.choice( util.list_entries() )
    if selected_title == None:
        message = f"Surprise article not available {selected_title}"

    article = util.print_markdown( util.get_entry( selected_title ) )
    
    return render( request, "encyclopedia/title.html", 
                    {
                        "article": article, 
                        "title": selected_title,
                        "message": message
                    } 
                  )

encyclopedia/templates/encyclopedia/addTitle.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - New article
{% endblock %}

{% block body %}
        <h2> New article</h2>
        <div class="container">
        <form action="{% url 'wiki:addTitle' %}" method="post">
            {% csrf_token %}
                {{ NewArticle.as_p }}
            <input type="submit" />
        </form>
        <h2> {{ message}}</h2>
        </div>
{% endblock %}

encyclopedia/templates/encyclopedia/editTitle.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ NewArticle.Title.value }}, edit article
{% endblock %}

{% block body %}
        <h2> Edit article</h2>
        <div class="container">
        <form method="post">
            {% csrf_token %}
                {{ NewArticle.as_p }}
                <br />
            <input type="submit" />
        </form>
        </div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
{% if message == None %}
    <h1>All Pages</h1>
{% else %}
    <h2>{{ message }} </h2>
{% endif %}
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:index' %}{{ entry }}" class="search">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:addTitle' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_title' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %}
    {% if message != None %}
        <div class="errorMsg">{{ message }}</div>
    {% endif %}

    {% if article != None %}
        <h2>{{ title }}</h2>
        <BR>
        {{ article|safe}}
        <a href= "{% url 'wiki:edit_title' title %}" class="search">Edit this article</a>
    {% endif %}
{% endblock %}